apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.43-192.168.1.44
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pihole-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - pihole-pool