apiVersion: v1
kind: Service
metadata:
  name: adhan-api
  namespace: adhan
spec:
  selector:
    app: adhan-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}