{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-increaser-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: {{ .schedule | default $.Values.defaultSchedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ $.Values.historyLimit.success }}
  failedJobsHistoryLimit: {{ $.Values.historyLimit.failed }}
  jobTemplate:
    spec:
      backoffLimit: {{ $.Values.backoffLimit }}
      activeDeadlineSeconds: {{ $.Values.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ $.Values.ttlSecondsAfterFinished }}
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: increaser
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              args:
                - "--package"
                - {{ .package | quote }}
                - "--num"
                - {{ .num | quote }}
                - "--max"
                - {{ .max | quote }}
              resources:
{{ toYaml $.Values.resources | indent 16 }}
{{- end }}
