apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: {{ .Values.unbound.image }}
          ports:
            - containerPort: {{ .Values.unbound.port }}
          volumeMounts:
            - name: unbound-config
              mountPath: /etc/unbound/custom.conf.d/custom.conf
              subPath: custom.conf
          resources:
{{ toYaml .Values.resources.unbound | indent 12 }}
      volumes:
        - name: unbound-config
          configMap:
            name: unbound-config