apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: increaser
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aminekun90/k8s-project.git
    targetRevision: main
    path: helm-charts/increaser
  destination:
    server: https://kubernetes.default.svc
    namespace: increaser
  # Auto-sync: the cluster follows git automatically.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
