---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  type: {{ .Values.service.dns.type }}
  {{- if .Values.service.dns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.dns.loadBalancerIP }}
  {{- end }}
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
spec:
  type: {{ .Values.service.web.type }}
  selector:
    app: pihole
  ports:
    - name: web
      port: {{ .Values.service.web.port }}
      targetPort: 80
      {{- if eq .Values.service.web.type "NodePort" }}
      nodePort: {{ .Values.service.web.nodePort }}
      {{- end }}
  {{- if .Values.service.web.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.web.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.web.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.web.loadBalancerIP }}
  {{- end }}