# templates/unbound-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: unbound
spec:
  type: ClusterIP
  selector:
    app: unbound
  ports:
    - name: dns-udp
      port: {{ .Values.unbound.port }}
      targetPort: {{ .Values.unbound.port }}
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.unbound.port }}
      targetPort: {{ .Values.unbound.port }}
      protocol: TCP